language: node_js
node_js:
- '0.12'
- '5.1'
sudo: false
env:
  matrix:
  - GROUP=
  global:
  - GH_REF: github.com/jupyterlab/services.git
  - secure: VksMSktfsYS7q60EhjFK+acMlRSgDbMYZ67djRy6Gu17C8e3fBpXgZHT1d9RB9eN1GGji3l889ocUOmvcR5bD/0GgidPwTwQpZnDsrTX5O7TbinKP8K228V/hGfPWhEC5lIViRGISzZkxrQmEA+TIcIqqPY6rRCoXMGzV/EVHztFFLzTeAhLPg/9cp1U24ZlLpz2n/a+rIaOASj9KVLDwwj3gGduzrwszP4idZlkFd6pgvSUn1J/YL+9IseI2+H0G/9ybEmPWPSOdOkrK6yeg7KpKaF9PDoxyik3vAnWfdO6JV/AsyWc2zcZmobf2pJ/m0W8hvsUlFsg0fBzOX6rf7U78orahPt+1o5+9M2mI48G5itazbXeVNi/7hedJM0Zj0g9sEQsnxzCMDcFEUVF8tqd2fShDdgEFAaCTVn2DMGk+kSCjcfXHj0OZs51IHMVZdihlliwYaPxaQrbQYvf0E7RyeDs512RSc5k3ivd/OjwIdFVoL0u4e+aJL3YVGTY4qA51K0wTi++IPVqbnZ7R1GnmtBiTD5Yl1KpyGqdW3fvH4YISAXT8t+O5Bze6AnaNd/zRUsiUQfq4rDabptA1u5P6lEzgnwthKSnh2OLDlMV+XVw92gOfRTTPlL4In8hWoytPJWWQBNaHu1sY7f24TGudX/ERwddkSJzBzYbqb0=
install:
- bash ./scripts/travis_install.sh
script:
- bash ./scripts/travis_script.sh
after_success:
- bash ./scripts/travis_after_success.sh
